version: '3.9'

services:
  
  app:
    build : ./app
    volumes:
      - ./app/:/usr/src/app
      - /usr/src/app/node_modules/ # make node_module empty in container
    command: npm start
    ports:
      - "3000:3000"

  postgres:
    #image: postgres
    build: ./postgres
    container_name: postgres
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb
    command: postgres
    volumes:
      - postgres:/data/postgres

  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports: 
      - 8081:8081
    links: 
      - postgres:postgres
    environment:
      - DATABASE_URL=postgres://postgres:example@postgres:5432/mydb?sslmode=disable
    depends_on:
      - postgres

volumes:
  postgres:
